node_id: "rtk_base"
measurement_rate_hz: 5
save_to_flash: false
publish_standard_topics: true
dynamic_model: 2

timepulse:
  active: true
  fixed_pulse:
    frequency: 1
    pulse_width: 0.1
  polarity: rising

rtk:
  mode: base
  base:
    type: survey_in
    min_observation_time_s: 180
    required_accuracy_m: 50.0
